In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv(r"C:\Users\varun\Downloads\Sidewalk_Management_Database_-_Built.csv")
df

,BBLID,DOT_CONTSTRUCT_DATE,DBO,DBO_Date,CONTRACT,ATDByStreetTree,PortionofDefectByStreetTree,NoneofDefectByStreetTree,TotalSQFTSidewalkRepaired,TotalLFCurbRepaired,TotalCostToConstruct,TotalSQFTSDWRepairedStreetTreeOnly,TotalLFCurbRepairedStreetTreeOnly,TotalCostofRepairStreetTreeOnly
0,724002,03/22/2022,NaN,NaN,HWS2020Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,726250,11/03/2021,NaN,NaN,HWS2020Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,750040,03/22/2022,NaN,NaN,HWS2020Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,757885,03/21/2022,NaN,NaN,HWS2020Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,758005,10/18/2021,NaN,NaN,HWS2020Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104090,242340,06/10/2024,NaN,NaN,HWS2021XM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104091,144174,10/23/2024,NaN,NaN,HWS2021X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104092,167985,06/13/2024,NaN,NaN,HWS2021X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104093,60205,07/29/2024,NaN,NaN,HWS2021XM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104094,952740,11/26/2024,NaN,NaN,HWS2021R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN